using System;
using DecisionDriven.Analyzers.Generation;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace DecisionDriven.Analyzers.Rules;

/// <summary>
/// Which syntax trees of one compilation are generated code, by this package's definition rather
/// than Roslyn's.
/// </summary>
/// <remarks>
/// <para>
/// <c>RuleTiers.GeneratedCodeIsExempt</c>. A tree is generated when a source generator produced it
/// in this compilation, when its file is named <c>*.g.cs</c>, <c>*.generated.cs</c> or
/// <c>*.designer.cs</c>, when it lies in the project's intermediate output directory, where build
/// tasks write the files they generate (<c>AssemblyInfo.cs</c>, a test platform's entry point), or
/// when it lies under the NuGet package root, where a package's content files are compiled from.
/// The last is not generated in the usual sense, but it is the same case: the code is its author's,
/// not the consumer's, and the consumer cannot edit it.
/// </para>
/// <para>
/// Roslyn's own definition is wider: it also takes an <c>&lt;auto-generated&gt;</c> header,
/// <c>[GeneratedCode]</c> on a symbol, <c>generated_code = true</c> in .editorconfig, and names such
/// as <c>*.g.i.cs</c> and <c>TemporaryGeneratedFile_*</c>. Those are
/// requests for the rules to look away, written into code or configuration that is not generated,
/// and each is available to anyone. The rules still skip what Roslyn calls generated - that is
/// Roslyn's to decide - so DD0008 reports every such request in a tree this definition does not
/// cover, the way it reports a pragma.
/// </para>
/// </remarks>
internal sealed class GeneratedCode
{
    /// <summary>
    /// Made visible to the analyzers by the package's props. The SDK makes <c>ProjectDir</c>
    /// visible on its own.
    /// </summary>
    private const string IntermediateOutputPathOption = "build_property.IntermediateOutputPath";

    private const string ProjectDirOption = "build_property.ProjectDir";

    /// <summary>Made visible to the analyzers by the package's props.</summary>
    private const string NuGetPackageRootOption = "build_property.NuGetPackageRoot";

    private static readonly string[] GeneratedNameSuffixes = { ".g.cs", ".generated.cs", ".designer.cs" };

    /// <summary>
    /// The directory every source generator's output is rooted in for this compilation, ending in a
    /// slash, or empty when an in-memory driver rooted it nowhere; null when it is not known.
    /// </summary>
    private readonly string? generatorRoot;

    /// <summary>The project's intermediate output directory, ending in a slash, or null.</summary>
    private readonly string? intermediateDirectory;

    /// <summary>The NuGet package root, ending in a slash, or null when it is not known.</summary>
    private readonly string? packageRoot;

    private GeneratedCode(string? generatorRoot, string? intermediateDirectory, string? packageRoot)
    {
        this.generatorRoot = generatorRoot;
        this.intermediateDirectory = intermediateDirectory;
        this.packageRoot = packageRoot;
    }

    /// <summary>The definition as it applies to <paramref name="compilation"/>.</summary>
    internal static GeneratedCode For(Compilation compilation, AnalyzerConfigOptions globalOptions) =>
        new GeneratedCode(GeneratorRoot(compilation), IntermediateDirectory(globalOptions), PackageRoot(globalOptions));

    /// <summary>True when <paramref name="tree"/> is generated code by this package's definition.</summary>
    internal bool Contains(SyntaxTree tree)
    {
        string path = Normalise(tree.FilePath);

        return path.Length > 0
            && (IsNamedGenerated(path)
                || IsGeneratorOutput(path)
                || IsIn(path, intermediateDirectory)
                || IsIn(path, packageRoot));
    }

    /// <summary>True when the file's name marks it as generated.</summary>
    internal static bool IsNamedGenerated(string filePath)
    {
        foreach (string suffix in GeneratedNameSuffixes)
        {
            if (filePath.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// True when Roslyn treats the file as generated by its name: <c>TemporaryGeneratedFile_*</c>, or a
    /// name whose part before the extension ends in <c>.designer</c>, <c>.generated</c>, <c>.g</c> or
    /// <c>.g.i</c>. Wider than <see cref="IsNamedGenerated"/>; the difference is a look-away request.
    /// </summary>
    internal static bool IsNamedGeneratedByRoslyn(string filePath)
    {
        string path = Normalise(filePath);
        string name = path.Substring(path.LastIndexOf('/') + 1);

        if (name.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        int dot = name.LastIndexOf('.');
        if (dot <= 0)
        {
            return false;
        }

        string stem = name.Substring(0, dot);
        return stem.EndsWith(".designer", StringComparison.OrdinalIgnoreCase)
            || stem.EndsWith(".generated", StringComparison.OrdinalIgnoreCase)
            || stem.EndsWith(".g", StringComparison.OrdinalIgnoreCase)
            || stem.EndsWith(".g.i", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// A generated tree's path is <c>&lt;root&gt;/&lt;generator assembly&gt;/&lt;generator type&gt;/&lt;hint&gt;</c>,
    /// for every generator in the compilation.
    /// </summary>
    /// <remarks>
    /// The root is read from where this package's own generator put its output
    /// (<see cref="GeneratorIdentity.OutputDirectory"/>), which a hand-written file cannot move: the
    /// same anchor DD0007 uses for provenance. A path with the right shape anywhere else is not
    /// generator output.
    /// </remarks>
    private bool IsGeneratorOutput(string path)
    {
        if (generatorRoot is null || !path.StartsWith(generatorRoot, StringComparison.Ordinal))
        {
            return false;
        }

        // An in-memory driver roots output nowhere, so its trees have relative paths; a file on disk
        // never does.
        if (generatorRoot.Length == 0 && IsRooted(path))
        {
            return false;
        }

        string rest = path.Substring(generatorRoot.Length);
        int first = rest.IndexOf('/');
        int second = first < 0 ? -1 : rest.IndexOf('/', first + 1);

        return first > 0 && second > first + 1 && second < rest.Length - 1;
    }

    private static string? GeneratorRoot(Compilation compilation)
    {
        if (GeneratorIdentity.OutputDirectory(compilation) is not { } directory
            || !directory.EndsWith(GeneratorIdentity.TreePathPrefix, StringComparison.Ordinal))
        {
            return null;
        }

        return directory.Substring(0, directory.Length - GeneratorIdentity.TreePathPrefix.Length);
    }

    private static string? IntermediateDirectory(AnalyzerConfigOptions options)
    {
        if (!options.TryGetValue(IntermediateOutputPathOption, out string? intermediate)
            || intermediate is not { Length: > 0 })
        {
            return null;
        }

        string path = Normalise(intermediate.Trim());

        if (!IsRooted(path))
        {
            if (!options.TryGetValue(ProjectDirOption, out string? projectDir) || projectDir is not { Length: > 0 })
            {
                return null;
            }

            path = WithSlash(Normalise(projectDir.Trim())) + path;
        }

        return WithSlash(Collapse(path));
    }

    /// <summary>
    /// The package root is always absolute. A relative value is not something NuGet writes, and is
    /// ignored rather than resolved against a guess.
    /// </summary>
    private static string? PackageRoot(AnalyzerConfigOptions options)
    {
        if (!options.TryGetValue(NuGetPackageRootOption, out string? root) || root is not { Length: > 0 })
        {
            return null;
        }

        string path = Normalise(root.Trim());
        return IsRooted(path) ? WithSlash(Collapse(path)) : null;
    }

    /// <remarks>
    /// Case-insensitive: MSBuild and the compiler can disagree on a Windows drive letter's case, and
    /// two directories differing only in case under one project are not a distinction worth a false
    /// positive.
    /// </remarks>
    private static bool IsIn(string path, string? directory) =>
        directory is not null && path.StartsWith(directory, StringComparison.OrdinalIgnoreCase);

    private static bool IsRooted(string path) =>
        path.StartsWith("/", StringComparison.Ordinal) || (path.Length > 1 && path[1] == ':');

    private static string Normalise(string path) => path.Replace('\\', '/');

    private static string WithSlash(string path) => path.EndsWith("/", StringComparison.Ordinal) ? path : path + "/";

    /// <summary>Removes <c>.</c> and <c>..</c> segments, since MSBuild may hand either over.</summary>
    private static string Collapse(string path)
    {
        string[] parts = path.Split('/');
        System.Collections.Generic.List<string> kept = new System.Collections.Generic.List<string>(parts.Length);

        for (int i = 0; i < parts.Length; i++)
        {
            string part = parts[i];

            if (part == "." || (part.Length == 0 && i > 0 && i < parts.Length - 1))
            {
                continue;
            }

            if (part == ".." && kept.Count > 1)
            {
                kept.RemoveAt(kept.Count - 1);
                continue;
            }

            kept.Add(part);
        }

        return string.Join("/", kept);
    }
}
