using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using DecisionDriven.Analyzers.Rules;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Xunit;

namespace DecisionDriven.Analyzers.Tests.Rules;

/// <summary>
/// <c>RuleTiers.GeneratedCodeIsExempt</c>: code is generated only if a source generator produced it in
/// this compilation, its file is named <c>*.g.cs</c>, <c>*.generated.cs</c> or <c>*.designer.cs</c>, or
/// it lies in the project's intermediate output directory. Every rule but DD0008 skips generated code;
/// every other way of asking Roslyn to skip code is a DD0008 finding.
/// </summary>
/// <remarks>
/// A generated declaration is the generator author's decision, not the consumer's, so a rule that
/// reported it would ask the consumer a question only somebody else can answer. An
/// <c>&lt;auto-generated&gt;</c> header typed into a hand-written file makes no generator its author;
/// it is a suppression with no citation. DD0008's own cases, messages included, are in
/// <see cref="SuppressionTests"/>.
/// </remarks>
public sealed class GeneratedCodeTests
{
    private const string Stub =
        "namespace Consumer { public sealed class Thing { public void Run() => throw new System.NotImplementedException(); } }";

    [Fact]
    public void Every_rule_but_DD0008_skips_generated_code_and_DD0008_reports_in_it()
    {
        // Asked of the assembly, like the smoke test, so a rule added later is held to the
        // decision the moment it exists.
        List<string> wrong = new List<string>();

        foreach (DiagnosticAnalyzer analyzer in AnalyzerPackage.Analyzers)
        {
            RecordingContext context = new RecordingContext();
            analyzer.Initialize(context);

            bool isDd0008 = analyzer.SupportedDiagnostics.Any(static d => d.Id == "DD0008");
            GeneratedCodeAnalysisFlags expected = isDd0008
                ? GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics
                : GeneratedCodeAnalysisFlags.None;

            if (context.Flags != expected)
            {
                wrong.Add($"{analyzer.GetType().Name}: {context.Flags?.ToString() ?? "not configured"}, expected {expected}");
            }
        }

        Assert.NotEmpty(AnalyzerPackage.Analyzers);
        Assert.Empty(wrong);
    }

    [Theory]
    [InlineData("Stub.g.cs")]
    [InlineData("Stub.generated.cs")]
    [InlineData("Stub.Designer.cs")]
    public void A_file_named_as_generated_is_exempt(string path)
    {
        CSharpCompilation compilation = Compile(path, Stub);

        Assert.Empty(RuleHarness.RunOn(new NotImplementedAnalyzer(), compilation));
        Assert.Empty(RuleHarness.RunOn(new SuppressionAnalyzer(), compilation));
    }

    [Fact]
    public void A_build_tasks_file_in_the_intermediate_output_directory_is_exempt()
    {
        // As the SDK writes AssemblyInfo.cs: a header, in obj/. The header is what makes Roslyn skip
        // it; the directory is what makes the header not a request to look away.
        string project = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "src", "Consumer");
        string path = System.IO.Path.Combine(project, "obj", "Release", "net10.0", "Consumer.AssemblyInfo.cs");
        CSharpCompilation compilation = Compile(path, "// <auto-generated/>\n" + Stub);
        Dictionary<string, string> properties = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["build_property.ProjectDir"] = project + System.IO.Path.DirectorySeparatorChar,
            ["build_property.IntermediateOutputPath"] = "obj/Release/net10.0/",
        };

        Assert.Empty(RuleHarness.RunOn(new NotImplementedAnalyzer(), compilation, properties));
        Assert.Empty(RuleHarness.RunOn(new SuppressionAnalyzer(), compilation, properties));
    }

    [Theory]
    [InlineData("Hand.cs", "// <auto-generated/>\n", "")]
    [InlineData("Hand.cs", "", "[System.CodeDom.Compiler.GeneratedCode(\"tool\", \"1.0\")]")]
    [InlineData("Hand.g.i.cs", "", "")]
    [InlineData("TemporaryGeneratedFile_Hand.cs", "", "")]
    public void Every_other_way_to_look_away_silences_the_rules_and_is_a_DD0008_finding(string path, string header, string attribute)
    {
        // The pair is the point: Roslyn honours each of these, so DD0018 goes quiet, and DD0008 is
        // what keeps that from being silent.
        CSharpCompilation compilation = Compile(path, header + Stub.Replace("public sealed class", attribute + " public sealed class", StringComparison.Ordinal));

        Assert.Empty(RuleHarness.RunOn(new NotImplementedAnalyzer(), compilation));
        Assert.Equal("DD0008", Assert.Single(RuleHarness.RunOn(new SuppressionAnalyzer(), compilation)).Id);
    }

    [Fact]
    public void Editorconfig_generated_code_silences_the_rules_and_is_a_DD0008_finding()
    {
        // Roslyn reads generated_code from the compilation's tree options, and analyzers see it as an
        // .editorconfig option; a real build supplies both from one section, so the test does too.
        CSharpCompilation compilation = Compile("Hand.cs", Stub);
        compilation = compilation.WithOptions(compilation.Options.WithSyntaxTreeOptionsProvider(new MarkedGenerated("Hand.cs")));
        Dictionary<string, Dictionary<string, string>> section = new Dictionary<string, Dictionary<string, string>>(StringComparer.Ordinal)
        {
            ["Hand.cs"] = new Dictionary<string, string>(StringComparer.Ordinal) { ["generated_code"] = "true" },
        };

        Assert.Empty(RuleHarness.RunOn(new NotImplementedAnalyzer(), compilation, fileOptions: section));
        Assert.Equal("DD0008", Assert.Single(RuleHarness.RunOn(new SuppressionAnalyzer(), compilation, fileOptions: section)).Id);
    }

    [Fact]
    public void The_same_violation_written_by_hand_is_reported()
    {
        // The control: without it the cases above would pass for a rule that reported nothing.
        Diagnostic diagnostic = Assert.Single(RuleHarness.RunOn(new NotImplementedAnalyzer(), Compile("Stub.cs", Stub)));

        Assert.Equal("DD0018", diagnostic.Id);
    }

    private static CSharpCompilation Compile(string path, string source) =>
        CSharpCompilation.Create(
            "Sample.Layer1",
            new[] { CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Latest), path) },
            RuleHarness.PlatformReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

    /// <summary>What a compiler builds from an .editorconfig section setting <c>generated_code = true</c>.</summary>
    private sealed class MarkedGenerated : SyntaxTreeOptionsProvider
    {
        private readonly string path;

        internal MarkedGenerated(string path)
        {
            this.path = path;
        }

        public override GeneratedKind IsGenerated(SyntaxTree tree, System.Threading.CancellationToken cancellationToken) =>
            tree.FilePath == path ? GeneratedKind.MarkedGenerated : GeneratedKind.Unknown;

        public override bool TryGetDiagnosticValue(SyntaxTree tree, string diagnosticId, System.Threading.CancellationToken cancellationToken, out ReportDiagnostic severity)
        {
            severity = ReportDiagnostic.Default;
            return false;
        }

        public override bool TryGetGlobalDiagnosticValue(string diagnosticId, System.Threading.CancellationToken cancellationToken, out ReportDiagnostic severity)
        {
            severity = ReportDiagnostic.Default;
            return false;
        }
    }

    /// <summary>
    /// Records what an analyzer asks for about generated code, and ignores everything else it
    /// registers.
    /// </summary>
    private sealed class RecordingContext : AnalysisContext
    {
        internal GeneratedCodeAnalysisFlags? Flags { get; private set; }

        public override void ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags analysisMode) => Flags = analysisMode;

        public override void EnableConcurrentExecution()
        {
        }

        public override void RegisterCompilationStartAction(Action<CompilationStartAnalysisContext> action)
        {
        }

        public override void RegisterCompilationAction(Action<CompilationAnalysisContext> action)
        {
        }

        public override void RegisterSemanticModelAction(Action<SemanticModelAnalysisContext> action)
        {
        }

        public override void RegisterSymbolAction(Action<SymbolAnalysisContext> action, ImmutableArray<SymbolKind> symbolKinds)
        {
        }

        public override void RegisterCodeBlockStartAction<TLanguageKindEnum>(Action<CodeBlockStartAnalysisContext<TLanguageKindEnum>> action)
        {
        }

        public override void RegisterCodeBlockAction(Action<CodeBlockAnalysisContext> action)
        {
        }

        public override void RegisterSyntaxTreeAction(Action<SyntaxTreeAnalysisContext> action)
        {
        }

        public override void RegisterSyntaxNodeAction<TLanguageKindEnum>(Action<SyntaxNodeAnalysisContext> action, ImmutableArray<TLanguageKindEnum> syntaxKinds)
        {
        }
    }
}
