using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using DecisionDriven.Analyzers.Rules;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Xunit;

namespace DecisionDriven.Analyzers.Tests.Rules;

/// <summary>
/// <c>RuleTiers.GeneratedCodeIsExempt</c>: every rule skips generated code except DD0008.
/// </summary>
/// <remarks>
/// A generated declaration is the generator author's decision, not the consumer's, so a rule
/// that reported it would ask the consumer a question only somebody else can answer. DD0008 is
/// the exception because a generated pragma silences a rule as thoroughly as a written one; its
/// behaviour in generated files is tested with the rest of it, in <see cref="SuppressionTests"/>.
/// </remarks>
public sealed class GeneratedCodeTests
{
    private const string Stub =
        "namespace Consumer { public sealed class Thing { public void Run() => throw new System.NotImplementedException(); } }";

    [Fact]
    public void Every_rule_but_DD0008_skips_generated_code_and_DD0008_reports_in_it()
    {
        // Asked of the assembly, like the smoke test, so a rule added later is held to the
        // decision the moment it exists.
        List<string> wrong = new List<string>();

        foreach (DiagnosticAnalyzer analyzer in AnalyzerPackage.Analyzers)
        {
            RecordingContext context = new RecordingContext();
            analyzer.Initialize(context);

            bool isDd0008 = analyzer.SupportedDiagnostics.Any(static d => d.Id == "DD0008");
            GeneratedCodeAnalysisFlags expected = isDd0008
                ? GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics
                : GeneratedCodeAnalysisFlags.None;

            if (context.Flags != expected)
            {
                wrong.Add($"{analyzer.GetType().Name}: {context.Flags?.ToString() ?? "not configured"}, expected {expected}");
            }
        }

        Assert.NotEmpty(AnalyzerPackage.Analyzers);
        Assert.Empty(wrong);
    }

    [Theory]
    [InlineData("Stub.g.cs", "")]
    [InlineData("Stub.cs", "// <auto-generated/>\n")]
    public void A_violation_in_generated_code_is_not_reported(string path, string header)
    {
        Assert.Empty(RuleHarness.RunOn(new NotImplementedAnalyzer(), Compile(path, header + Stub)));
    }

    [Fact]
    public void The_same_violation_written_by_hand_is_reported()
    {
        // The control: without it the two cases above would pass for a rule that reported nothing.
        Diagnostic diagnostic = Assert.Single(RuleHarness.RunOn(new NotImplementedAnalyzer(), Compile("Stub.cs", Stub)));

        Assert.Equal("DD0018", diagnostic.Id);
    }

    private static CSharpCompilation Compile(string path, string source) =>
        CSharpCompilation.Create(
            "Sample.Layer1",
            new[] { CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Latest), path) },
            RuleHarness.PlatformReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

    /// <summary>
    /// Records what an analyzer asks for about generated code, and ignores everything else it
    /// registers.
    /// </summary>
    private sealed class RecordingContext : AnalysisContext
    {
        internal GeneratedCodeAnalysisFlags? Flags { get; private set; }

        public override void ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags analysisMode) => Flags = analysisMode;

        public override void EnableConcurrentExecution()
        {
        }

        public override void RegisterCompilationStartAction(Action<CompilationStartAnalysisContext> action)
        {
        }

        public override void RegisterCompilationAction(Action<CompilationAnalysisContext> action)
        {
        }

        public override void RegisterSemanticModelAction(Action<SemanticModelAnalysisContext> action)
        {
        }

        public override void RegisterSymbolAction(Action<SymbolAnalysisContext> action, ImmutableArray<SymbolKind> symbolKinds)
        {
        }

        public override void RegisterCodeBlockStartAction<TLanguageKindEnum>(Action<CodeBlockStartAnalysisContext<TLanguageKindEnum>> action)
        {
        }

        public override void RegisterCodeBlockAction(Action<CodeBlockAnalysisContext> action)
        {
        }

        public override void RegisterSyntaxTreeAction(Action<SyntaxTreeAnalysisContext> action)
        {
        }

        public override void RegisterSyntaxNodeAction<TLanguageKindEnum>(Action<SyntaxNodeAnalysisContext> action, ImmutableArray<TLanguageKindEnum> syntaxKinds)
        {
        }
    }
}
