namespace DecisionDriven.Analyzers.Generation;

/// <summary>
/// The marker attributes, emitted into every consuming compilation.
/// </summary>
/// <remarks>
/// <para>
/// <c>DecisionsAsTypes.AttributesAreSourceGenerated</c>. They are emitted rather than shipped in a
/// runtime assembly because the package is development-time only
/// (<c>TwoPackages.DevelopmentTimeOnly</c>): a consumer that referenced an annotations assembly
/// would carry it at runtime and expose it on its own public surface. Emitted <c>internal</c>, they
/// are matched by full name across assemblies, so every project has its own copy and none of them
/// is a dependency.
/// </para>
/// <para>
/// This source is fixed. It is added at post-initialization so it exists before anything is parsed,
/// which is what lets a consumer write <c>[Contract(...)]</c> in the same compilation that generates
/// the attribute.
/// </para>
/// </remarks>
internal static class GeneratedAttributes
{
    /// <summary>The hint name the source is added under.</summary>
    internal const string HintName = "DecisionDriven.Attributes.g.cs";

    /// <summary>The source text.</summary>
    internal const string Text = @"// <auto-generated/>
// Emitted by DecisionDriven.Analyzers. Do not edit; edit the generator.
#nullable enable

namespace DecisionDriven
{
    /// <summary>The layer a whole assembly sits at, from the ArchLayer MSBuild property.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
    internal sealed class ArchLayerAttribute : global::System.Attribute
    {
        public ArchLayerAttribute(int layer)
        {
            Layer = layer;
        }

        public int Layer { get; }
    }

    /// <summary>Marks a type as a contract, citing the decision that made it one.</summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Interface | global::System.AttributeTargets.Class | global::System.AttributeTargets.Delegate,
        AllowMultiple = false)]
    internal sealed class ContractAttribute : global::System.Attribute
    {
        public ContractAttribute(global::System.Type decision)
        {
            Decision = decision;
        }

        public global::System.Type Decision { get; }

        /// <summary>A label for what side of the boundary this contract is. Not a justification.</summary>
        public string Role { get; set; } = string.Empty;
    }

    /// <summary>Declares a namespace prefix of this assembly to be domain model.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
    internal sealed class DomainModelAttribute : global::System.Attribute
    {
        public DomainModelAttribute(string namespacePrefix, global::System.Type decision)
        {
            NamespacePrefix = namespacePrefix;
            Decision = decision;
        }

        public string NamespacePrefix { get; }

        public global::System.Type Decision { get; }
    }

    /// <summary>Marks code whose cost is measured, citing the decision that says so.</summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Method | global::System.AttributeTargets.Property
            | global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
        AllowMultiple = false)]
    internal sealed class HotPathAttribute : global::System.Attribute
    {
        public HotPathAttribute(global::System.Type decision)
        {
            Decision = decision;
        }

        public global::System.Type Decision { get; }
    }

    /// <summary>
    /// The only way to accept a violation of a DD rule. Cites the decision that permits it and says
    /// which kind of exception it is.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.All, AllowMultiple = true)]
    internal sealed class DesignDecisionAttribute : global::System.Attribute
    {
        public DesignDecisionAttribute(global::System.Type decision)
        {
            Decision = decision;
        }

        public global::System.Type Decision { get; }

        public ExceptionScope Scope { get; set; }
    }

    /// <summary>
    /// The closed set of reasons a documented exception can have. Closed on purpose: a free-text
    /// reason is a justification nobody reads, and these six mirror a SKOS scheme in the ledger so
    /// the report tool emits the same tokens.
    /// </summary>
    internal enum ExceptionScope
    {
        Boundary,
        HotPath,
        Pool,
        Interop,
        Compatibility,
        Migration,
    }
}
";
}
