using System.Collections.Generic;
using System.Text;
using DecisionDriven.Analyzers.Ledger;

namespace DecisionDriven.Analyzers.Generation;

/// <summary>
/// Turns the ledger model into the decision types code cites.
/// </summary>
/// <remarks>
/// <c>DecisionsAsTypes.OneTypePerSetNestedTypePerDecision</c>: one static class per set, one nested
/// static class per decision named by its key, in <c>DecisionDriven.Ledger.&lt;namespace&gt;</c>.
/// Membership follows the tip version's set, so moving a decision between sets moves the type.
/// </remarks>
internal static class LedgerEmitter
{
    /// <summary>
    /// Emits one file per ledger namespace.
    /// </summary>
    /// <returns>Hint name to source text.</returns>
    internal static IEnumerable<KeyValuePair<string, string>> Emit(Dictionary<string, LedgerNamespace> namespaces)
    {
        List<string> names = new List<string>(namespaces.Keys);
        names.Sort(System.StringComparer.Ordinal);

        foreach (string name in names)
        {
            LedgerNamespace ns = namespaces[name];
            string source = EmitNamespace(ns);

            if (source.Length > 0)
            {
                yield return new KeyValuePair<string, string>(
                    "DecisionDriven.Ledger." + Identifiers.ToPascalCase(name) + ".g.cs",
                    source);
            }
        }
    }

    private static string EmitNamespace(LedgerNamespace ns)
    {
        // Group by the tip version's set. A decision with no tip, or a tip with no set or no key,
        // is not emitted: the diagnostics have already said why, and emitting a half-formed type
        // would turn one clear error into a cascade of "type not found" at every citation.
        SortedDictionary<string, SortedDictionary<string, Decision>> bySet =
            new SortedDictionary<string, SortedDictionary<string, Decision>>(System.StringComparer.Ordinal);

        foreach (Decision decision in ns.Decisions.Values)
        {
            DecisionVersion? tip = decision.Tip;
            if (tip?.SetId is not { Length: > 0 } setId || tip.Key is not { Length: > 0 } key)
            {
                continue;
            }

            if (!DecisionKey.IsValid(key))
            {
                continue;
            }

            if (!bySet.TryGetValue(setId, out SortedDictionary<string, Decision>? decisions))
            {
                decisions = new SortedDictionary<string, Decision>(System.StringComparer.Ordinal);
                bySet.Add(setId, decisions);
            }

            // A duplicate key is reported by DDGEN0001; emitting the first of them keeps the rest
            // of the namespace compiling instead of losing every type in it to one bad pair.
            if (!decisions.ContainsKey(key))
            {
                decisions.Add(key, decision);
            }
        }

        if (bySet.Count == 0)
        {
            return string.Empty;
        }

        StringBuilder builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n");
        builder.Append("// Emitted by DecisionDriven.Analyzers from the decision ledger. Do not edit.\n");
        builder.Append("#nullable enable\n\n");
        builder.Append("namespace DecisionDriven.Ledger.").Append(Identifiers.ToPascalCase(ns.Name)).Append('\n');
        builder.Append("{\n");

        bool firstSet = true;
        foreach (KeyValuePair<string, SortedDictionary<string, Decision>> set in bySet)
        {
            if (!firstSet)
            {
                builder.Append('\n');
            }

            firstSet = false;
            EmitSet(builder, set.Key, set.Value);
        }

        builder.Append("}\n");
        return builder.ToString();
    }

    private static void EmitSet(StringBuilder builder, string setId, SortedDictionary<string, Decision> decisions)
    {
        builder.Append("    /// <summary>Decision set <c>").Append(EscapeXml(setId)).Append("</c>.</summary>\n");
        builder.Append("    internal static class ").Append(Identifiers.ToPascalCase(setId)).Append('\n');
        builder.Append("    {\n");
        builder.Append("        /// <summary>The set id as written in the ledger.</summary>\n");
        builder.Append("        public const string SetId = \"").Append(EscapeLiteral(setId)).Append("\";\n");

        foreach (KeyValuePair<string, Decision> pair in decisions)
        {
            builder.Append('\n');
            EmitDecision(builder, pair.Key, pair.Value);
        }

        builder.Append("    }\n");
    }

    private static void EmitDecision(StringBuilder builder, string key, Decision decision)
    {
        DecisionVersion tip = decision.Tip!;

        if (tip.Statement is { Length: > 0 } statement)
        {
            builder.Append("        /// <summary>").Append(EscapeXml(statement)).Append("</summary>\n");
        }

        // DecisionsAsTypes.RevokedEmitsErrorObsolete beats UnacceptedEmitsWarningObsolete: a revoked
        // decision is not merely unaccepted, and reporting it as unaccepted would understate it.
        // DecisionsAsTypes.SupersessionIsNotObsolescence: a successor means no attribute at all.
        if (decision.IsRevokedWithoutSuccessor)
        {
            builder.Append("        [global::System.Obsolete(\"Revoked ")
                .Append(EscapeLiteral(decision.RevokedAt!))
                .Append(": this decision no longer holds and has no successor to carry its key.\", error: true)]\n");
        }
        else if (!decision.TipIsAccepted)
        {
            builder.Append("        [global::System.Obsolete(\"Not accepted: the tip version of this decision has no unrevoked acceptance. ")
                .Append("It may be cited on a branch; a build with warnings as errors will not ship it.\", error: false)]\n");
        }

        builder.Append("        public static class ").Append(key).Append('\n');
        builder.Append("        {\n");
        builder.Append("            /// <summary>The decision's identity in the ledger.</summary>\n");
        builder.Append("            public const string Id = \"").Append(EscapeLiteral(decision.Id)).Append("\";\n");
        builder.Append("\n            /// <summary>The key, immutable across versions and carried across supersession.</summary>\n");
        builder.Append("            public const string Key = \"").Append(EscapeLiteral(key)).Append("\";\n");
        builder.Append("\n            /// <summary>The ledger namespace the decision lives in.</summary>\n");
        builder.Append("            public const string Namespace = \"").Append(EscapeLiteral(decision.Namespace)).Append("\";\n");
        builder.Append("        }\n");
    }

    /// <summary>
    /// For a C# string literal: quotes and backslashes only. A literal is not XML, and escaping
    /// angle brackets here would put "&amp;lt;" in the value a consumer reads back.
    /// </summary>
    private static string EscapeLiteral(string value)
    {
        StringBuilder builder = new StringBuilder(value.Length);

        foreach (char c in value)
        {
            switch (c)
            {
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '\r':
                    break;
                case '\n':
                    builder.Append(' ');
                    break;
                default:
                    builder.Append(c);
                    break;
            }
        }

        return builder.ToString();
    }

    /// <summary>
    /// For the inside of a doc comment: the three XML metacharacters, and newlines flattened so a
    /// multi-line statement cannot break out of its summary element.
    /// </summary>
    private static string EscapeXml(string value)
    {
        StringBuilder builder = new StringBuilder(value.Length);

        foreach (char c in value)
        {
            switch (c)
            {
                case '<':
                    builder.Append("&lt;");
                    break;
                case '>':
                    builder.Append("&gt;");
                    break;
                case '&':
                    builder.Append("&amp;");
                    break;
                case '\r':
                    break;
                case '\n':
                    builder.Append(' ');
                    break;
                default:
                    builder.Append(c);
                    break;
            }
        }

        return builder.ToString();
    }
}
